/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ooseproject_pages_views;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ooseproject_business_logic.Booking_Services;
import static ooseproject_pages_views.Home_Screen.logged_in_username;
import static ooseproject_pages_views.Login_Screen.user;

/**
 *
 * @author KK
 */
public class All_Booked_Screen extends javax.swing.JFrame {

    /**
     * Creates new form All_Booked_Screen
     */
    SimpleDateFormat sdfo = new SimpleDateFormat("yyyy-MM-dd");

    public All_Booked_Screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allbooked_panel = new javax.swing.JPanel();
        home_page_button = new javax.swing.JButton();
        cancel_booking = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        datatable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HBH - BOOKED");
        setLocation(new java.awt.Point(20, 20));
        setPreferredSize(new java.awt.Dimension(1325, 700));

        allbooked_panel.setBackground(new java.awt.Color(0, 153, 255));

        home_page_button.setBackground(new java.awt.Color(1, 215, 194));
        home_page_button.setFont(new java.awt.Font("Tw Cen MT", 2, 16)); // NOI18N
        home_page_button.setForeground(new java.awt.Color(255, 255, 255));
        home_page_button.setText("BACK");
        home_page_button.setBorder(null);
        home_page_button.setPreferredSize(new java.awt.Dimension(30, 16));
        home_page_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_page_buttonActionPerformed(evt);
            }
        });

        cancel_booking.setBackground(new java.awt.Color(1, 215, 194));
        cancel_booking.setFont(new java.awt.Font("Tw Cen MT", 2, 16)); // NOI18N
        cancel_booking.setForeground(new java.awt.Color(255, 255, 255));
        cancel_booking.setText("Cancel Booking");
        cancel_booking.setBorder(null);
        cancel_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_bookingActionPerformed(evt);
            }
        });

        datatable.setFont(new java.awt.Font("Source Code Pro", 1, 16)); // NOI18N
        datatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Fee", "Date", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        datatable.setRowHeight(30);
        jScrollPane2.setViewportView(datatable);
        if (datatable.getColumnModel().getColumnCount() > 0) {
            datatable.getColumnModel().getColumn(0).setPreferredWidth(300);
            datatable.getColumnModel().getColumn(1).setResizable(false);
            datatable.getColumnModel().getColumn(1).setPreferredWidth(400);
            datatable.getColumnModel().getColumn(2).setPreferredWidth(150);
            datatable.getColumnModel().getColumn(3).setPreferredWidth(200);
            datatable.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        javax.swing.GroupLayout allbooked_panelLayout = new javax.swing.GroupLayout(allbooked_panel);
        allbooked_panel.setLayout(allbooked_panelLayout);
        allbooked_panelLayout.setHorizontalGroup(
            allbooked_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allbooked_panelLayout.createSequentialGroup()
                .addGroup(allbooked_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allbooked_panelLayout.createSequentialGroup()
                        .addGap(538, 538, 538)
                        .addComponent(home_page_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(cancel_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(allbooked_panelLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1016, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        allbooked_panelLayout.setVerticalGroup(
            allbooked_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allbooked_panelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(allbooked_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home_page_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(allbooked_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(allbooked_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 809, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_page_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_page_buttonActionPerformed
        // TODO add your handling code here:
        new Home_Screen().setVisible(true);
        logged_in_username.setText(user.getName());
        this.dispose();
    }//GEN-LAST:event_home_page_buttonActionPerformed

    private void cancel_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_bookingActionPerformed
//         TODO add your handling code here:
        DefaultTableModel defaultTableModel = (DefaultTableModel) datatable.getModel();
        Date datenow = new Date();
        sdfo.format(datenow);
        
        if (datatable.getSelectedRowCount() == 1) {

            String name = defaultTableModel.getValueAt(datatable.getSelectedRow(), 0).toString();
            String date = defaultTableModel.getValueAt(datatable.getSelectedRow(), 3).toString();
            
            try {
                Date bookedDate = sdfo.parse(date);
                Date cancelDate = new Date(bookedDate.getTime() + 24*60*60*1000);
                if (datenow.after(cancelDate)){
                    JOptionPane.showMessageDialog(this, "Booking can be only cancelled with in 1 days");
                }
                else{
                    new Booking_Services().deletebooking(name);
                    defaultTableModel.removeRow(datatable.getSelectedRow());
                }
            } catch (ParseException ex) {
                Logger.getLogger(All_Booked_Screen.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Book Hostel First to Cancel");
        }
    }//GEN-LAST:event_cancel_bookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(All_Booked_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new All_Booked_Screen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allbooked_panel;
    private javax.swing.JButton cancel_booking;
    protected static javax.swing.JTable datatable;
    private javax.swing.JButton home_page_button;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
