/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ooseproject_pages_views;


import javax.swing.ImageIcon;
import ooseproject_business_logic.Hostel_Services;
import ooseproject_model.Hostel_Model;
import static ooseproject_pages_views.Hostel_Details_Screen.*;
import static ooseproject_pages_views.Home_Screen.logged_in_username;
import static ooseproject_pages_views.Login_Screen.user;
/**
 *
 * @author MR Laptop
 */
public class All_Hostels_Screen extends javax.swing.JFrame {

    /**
     * Creates new form 
     * @param m
     */
    private Hostel_Services hostel = new Hostel_Services();
    static int hostel_id;
    
    
    public static void setIndiviual(Hostel_Model m){
        name_label_set.setText(m.getHostel_name());
        email_label_set.setText(m.getHostel_email());
        address_label_set.setText(m.getHostel_address());
        type_label_set.setText(m.getHostel_type());
        room_label_set.setText(Integer.toString(m.getHostel_total_rooms()));
        fee_label_set.setText(Integer.toString(m.getHostel_fees()));
        mess_label_set.setText(m.getIsMess());
        hostel_image.setIcon(new ImageIcon(m.getBig_url()));
        hostel_id = m.getHostel_id();
    }
    
    public All_Hostels_Screen() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * D:\Java\ooseproject\images
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        image_3 = new javax.swing.JButton();
        image_4 = new javax.swing.JButton();
        image_2 = new javax.swing.JButton();
        image_6 = new javax.swing.JButton();
        image_5 = new javax.swing.JButton();
        image_1 = new javax.swing.JButton();
        hostel_name_1 = new javax.swing.JLabel();
        hostel_name_2 = new javax.swing.JLabel();
        hostel_name_4 = new javax.swing.JLabel();
        hostel_name_6 = new javax.swing.JLabel();
        hostel_name_5 = new javax.swing.JLabel();
        _backbutton = new javax.swing.JButton();
        hostel_name_3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HBH - ALL HOSTELS");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 153));
        setLocation(new java.awt.Point(20, 20));
        setPreferredSize(new java.awt.Dimension(1325, 700));

        jPanel1.setBackground(new java.awt.Color(1, 215, 194));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        image_3.setForeground(new java.awt.Color(51, 102, 255));
        image_3.setBorder(null);
        image_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image_3ActionPerformed(evt);
            }
        });

        image_4.setForeground(new java.awt.Color(51, 102, 255));
        image_4.setBorder(null);
        image_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image_4ActionPerformed(evt);
            }
        });

        image_2.setForeground(new java.awt.Color(51, 102, 255));
        image_2.setBorder(null);
        image_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image_2ActionPerformed(evt);
            }
        });

        image_6.setForeground(new java.awt.Color(51, 102, 255));
        image_6.setBorder(null);
        image_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image_6ActionPerformed(evt);
            }
        });

        image_5.setForeground(new java.awt.Color(51, 102, 255));
        image_5.setBorder(null);
        image_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image_5ActionPerformed(evt);
            }
        });

        image_1.setForeground(new java.awt.Color(51, 102, 255));
        image_1.setBorder(null);
        image_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image_1ActionPerformed(evt);
            }
        });

        hostel_name_1.setFont(new java.awt.Font("Source Code Pro", 0, 16)); // NOI18N
        hostel_name_1.setForeground(new java.awt.Color(255, 255, 255));
        hostel_name_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hostel_name_1.setText("Hostel 1");
        hostel_name_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        hostel_name_2.setFont(new java.awt.Font("Source Code Pro", 0, 16)); // NOI18N
        hostel_name_2.setForeground(new java.awt.Color(255, 255, 255));
        hostel_name_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hostel_name_2.setText("Hostel 2");
        hostel_name_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        hostel_name_4.setFont(new java.awt.Font("Source Code Pro", 0, 16)); // NOI18N
        hostel_name_4.setForeground(new java.awt.Color(255, 255, 255));
        hostel_name_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hostel_name_4.setText("Hostel 4");
        hostel_name_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        hostel_name_6.setFont(new java.awt.Font("Source Code Pro", 0, 16)); // NOI18N
        hostel_name_6.setForeground(new java.awt.Color(255, 255, 255));
        hostel_name_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hostel_name_6.setText("Hostel 6");
        hostel_name_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        hostel_name_5.setFont(new java.awt.Font("Source Code Pro", 0, 16)); // NOI18N
        hostel_name_5.setForeground(new java.awt.Color(255, 255, 255));
        hostel_name_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hostel_name_5.setText("Hostel 5");
        hostel_name_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        _backbutton.setBackground(new java.awt.Color(0, 153, 255));
        _backbutton.setFont(new java.awt.Font("Tw Cen MT", 2, 16)); // NOI18N
        _backbutton.setForeground(new java.awt.Color(255, 255, 255));
        _backbutton.setText("BACK");
        _backbutton.setToolTipText("");
        _backbutton.setBorder(null);
        _backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _backbuttonActionPerformed(evt);
            }
        });

        hostel_name_3.setFont(new java.awt.Font("Source Code Pro", 0, 16)); // NOI18N
        hostel_name_3.setForeground(new java.awt.Color(255, 255, 255));
        hostel_name_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hostel_name_3.setText("Hostel 3");
        hostel_name_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hostel_name_1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(image_4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hostel_name_4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(image_5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hostel_name_5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hostel_name_2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hostel_name_6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hostel_name_3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(image_6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 494, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(image_1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(image_2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(image_3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(609, 609, 609)
                .addComponent(_backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image_2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hostel_name_2)
                            .addComponent(hostel_name_1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(hostel_name_3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(image_4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(image_6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(image_5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hostel_name_4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hostel_name_5)
                        .addComponent(hostel_name_6)))
                .addGap(122, 122, 122)
                .addComponent(_backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 866, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void image_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image_1ActionPerformed
        // TODO add your handling code here:
        Hostel_Model mn = hostel.getOneHostel(hostel_name_1.getText());
        new Hostel_Details_Screen().setVisible(true);
        setIndiviual(mn);
        this.dispose();
    }//GEN-LAST:event_image_1ActionPerformed

    private void image_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image_2ActionPerformed
        // TODO add your handling code here:
        Hostel_Model mn = hostel.getOneHostel(hostel_name_2.getText());
        new Hostel_Details_Screen().setVisible(true);
        setIndiviual(mn);
        this.dispose();
    }//GEN-LAST:event_image_2ActionPerformed

    private void image_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image_3ActionPerformed
        // TODO add your handling code here:
        Hostel_Model mn = hostel.getOneHostel(hostel_name_3.getText());
        new Hostel_Details_Screen().setVisible(true);
        setIndiviual(mn);
        this.dispose();
    }//GEN-LAST:event_image_3ActionPerformed

    private void image_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image_4ActionPerformed
        // TODO add your handling code here:
        Hostel_Model mn = hostel.getOneHostel(hostel_name_4.getText());
        new Hostel_Details_Screen().setVisible(true);
        setIndiviual(mn);
        this.dispose();
    }//GEN-LAST:event_image_4ActionPerformed

    private void image_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image_5ActionPerformed
        // TODO add your handling code here:
        Hostel_Model mn = hostel.getOneHostel(hostel_name_5.getText());
        new Hostel_Details_Screen().setVisible(true);
        setIndiviual(mn);
        this.dispose();
    }//GEN-LAST:event_image_5ActionPerformed

    private void image_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image_6ActionPerformed
        // TODO add your handling code here:
        Hostel_Model mn = hostel.getOneHostel(hostel_name_6.getText());
        new Hostel_Details_Screen().setVisible(true);
        setIndiviual(mn);
        this.dispose();
    }//GEN-LAST:event_image_6ActionPerformed

    private void _backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__backbuttonActionPerformed
        // TODO add your handling code here:
        new Home_Screen().setVisible(true);
        logged_in_username.setText(user.getName());
        this.dispose();
    }//GEN-LAST:event__backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(All_Hostels_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(All_Hostels_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(All_Hostels_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(All_Hostels_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new All_Hostels_Screen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _backbutton;
    protected static javax.swing.JLabel hostel_name_1;
    protected static javax.swing.JLabel hostel_name_2;
    protected static javax.swing.JLabel hostel_name_3;
    protected static javax.swing.JLabel hostel_name_4;
    protected static javax.swing.JLabel hostel_name_5;
    protected static javax.swing.JLabel hostel_name_6;
    protected static javax.swing.JButton image_1;
    protected static javax.swing.JButton image_2;
    protected static javax.swing.JButton image_3;
    protected static javax.swing.JButton image_4;
    protected static javax.swing.JButton image_5;
    protected static javax.swing.JButton image_6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
