/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ooseproject_pages_views;

import core.ConectionC;
import core.PlaceHolder;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ooseproject_business_logic.Auth_Services;

/**
 *
 * @author KK
 */
public class Forget_Password_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Forget_Password_Screen
     */
    private Auth_Services auth = new Auth_Services();

    public Forget_Password_Screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        image_panel = new javax.swing.JPanel();
        iamge = new javax.swing.JLabel();
        image_panel2 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        new_password = new javax.swing.JTextField();
        confirm_password = new javax.swing.JTextField();
        change_password = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FORGET SCREEN");
        setLocation(new java.awt.Point(20, 20));
        setPreferredSize(new java.awt.Dimension(1325, 700));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image_panel.setBackground(new java.awt.Color(1, 215, 194));
        image_panel.setPreferredSize(new java.awt.Dimension(500, 500));

        iamge.setBackground(new java.awt.Color(255, 204, 204));
        iamge.setIcon(new javax.swing.ImageIcon("D:\\Java\\ooseproject\\images\\Login - Signup Screen.png")); // NOI18N

        javax.swing.GroupLayout image_panelLayout = new javax.swing.GroupLayout(image_panel);
        image_panel.setLayout(image_panelLayout);
        image_panelLayout.setHorizontalGroup(
            image_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(image_panelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(iamge, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        image_panelLayout.setVerticalGroup(
            image_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(image_panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(iamge, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        main_panel.add(image_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 96, 590, -1));

        image_panel2.setBackground(new java.awt.Color(0, 153, 255));
        image_panel2.setPreferredSize(new java.awt.Dimension(500, 500));

        username.setBackground(new java.awt.Color(0, 153, 255));
        username.setFont(new java.awt.Font("Sitka Display", 3, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setText("Enter Username");
        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });

        new_password.setBackground(new java.awt.Color(0, 153, 255));
        new_password.setFont(new java.awt.Font("Sitka Display", 3, 14)); // NOI18N
        new_password.setForeground(new java.awt.Color(255, 255, 255));
        new_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        new_password.setText("Enter New Password");
        new_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        new_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                new_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                new_passwordFocusLost(evt);
            }
        });

        confirm_password.setBackground(new java.awt.Color(0, 153, 255));
        confirm_password.setFont(new java.awt.Font("Sitka Display", 3, 14)); // NOI18N
        confirm_password.setForeground(new java.awt.Color(255, 255, 255));
        confirm_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirm_password.setText("Confirm New Password");
        confirm_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        confirm_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirm_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirm_passwordFocusLost(evt);
            }
        });

        change_password.setBackground(new java.awt.Color(0, 153, 255));
        change_password.setFont(new java.awt.Font("Tw Cen MT", 2, 16)); // NOI18N
        change_password.setForeground(new java.awt.Color(255, 255, 255));
        change_password.setText("CHANGE PASSWORD");
        change_password.setToolTipText("");
        change_password.setBorder(null);
        change_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_passwordActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 153, 255));
        back.setFont(new java.awt.Font("Tw Cen MT", 2, 16)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.setToolTipText("");
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout image_panel2Layout = new javax.swing.GroupLayout(image_panel2);
        image_panel2.setLayout(image_panel2Layout);
        image_panel2Layout.setHorizontalGroup(
            image_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(image_panel2Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(image_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, image_panel2Layout.createSequentialGroup()
                        .addGroup(image_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(new_password, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, image_panel2Layout.createSequentialGroup()
                        .addGroup(image_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(change_password, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(169, 169, 169))))
        );
        image_panel2Layout.setVerticalGroup(
            image_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(image_panel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(new_password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(change_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        main_panel.add(image_panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 96, 600, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
        if (username.getText().equals("Enter Username")) {
            username.setText(null);
            username.requestFocus();
            new PlaceHolder().removePlaceHolder(username);
        }
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
        if (username.getText().length() == 0) {
            new PlaceHolder().addPlaceHolder(username);
            username.setText("Enter Username");
        }
    }//GEN-LAST:event_usernameFocusLost

    private void new_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_passwordFocusGained
        // TODO add your handling code here:
        if (new_password.getText().equals("Enter New Password")) {
            new_password.setText(null);
            new_password.requestFocus();
            new PlaceHolder().removePlaceHolder(new_password);
        }
    }//GEN-LAST:event_new_passwordFocusGained

    private void new_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_passwordFocusLost
        // TODO add your handling code here:
        if (new_password.getText().length() == 0) {
            new PlaceHolder().addPlaceHolder(new_password);
            new_password.setText("Enter New Password");
        }
    }//GEN-LAST:event_new_passwordFocusLost

    private void confirm_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirm_passwordFocusGained
        // TODO add your handling code here:
        if (confirm_password.getText().equals("Confirm New Password")) {
            confirm_password.setText(null);
            confirm_password.requestFocus();
            new PlaceHolder().removePlaceHolder(confirm_password);
        }
    }//GEN-LAST:event_confirm_passwordFocusGained

    private void confirm_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirm_passwordFocusLost
        // TODO add your handling code here:
        if (confirm_password.getText().length() == 0) {
            new PlaceHolder().addPlaceHolder(confirm_password);
            confirm_password.setText("Confirm New Password");
        }
    }//GEN-LAST:event_confirm_passwordFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void change_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_passwordActionPerformed
        // TODO add your handling code here:
        auth.forgetPassword(username.getText(), new_password.getText(), confirm_password.getText());
    }//GEN-LAST:event_change_passwordActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new Login_Screen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forget_Password_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forget_Password_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forget_Password_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forget_Password_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Forget_Password_Screen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton change_password;
    private javax.swing.JTextField confirm_password;
    private javax.swing.JLabel iamge;
    private javax.swing.JPanel image_panel;
    private javax.swing.JPanel image_panel2;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField new_password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
